### ISSUE TITLE
CentOS 7 to AlmaLinux 8 Failed — Multiple Reasons?

### ISSUE THREAD

**Issue by gregarios** [plesk/centos2alma#89]
Failed: making the conversation!. The reason: Command '['/usr/bin/leapp', 'preupgrade']' returned non-zero exit status 1.

The log is attached.

[Server-Upgrade-Failed-log-20230427.txt.zip](https://github.com/plesk/centos2alma/files/11346744/Server-Upgrade-Failed-log-20230427.txt.zip)

**Comment by SandakovMM** [comment]
Hello @gregarios 

Thank you for contacting us. It seems that the problem is related to the conversion when old migrator repositories are enabled. To fix the problem, you could remove the repository. You could likely find it in the /etc/yum.repos.d/plesk-ext-panel-migrator.repo file.

I am currently investigating a better way to fix the problem within the tool itself.

**Comment by gregarios** [comment]
> To fix the problem, you could remove the repository. You could likely find it in the /etc/yum.repos.d/plesk-ext-panel-migrator.repo file.

Should I remove the plesk-migrator.repo file itself?

It contains:

`[plesk-migrator]
name=Plesk packages for migrator
baseurl=http://autoinstall.plesk.com/PMM_0.1.10/dist-rpm-CentOS-7-x86_64
enabled=1
gpgcheck=1
gpgkey=http://autoinstall.plesk.com/plesk.gpg

[plesk-migrator-tp]
name=Plesk 3d-party packages for migrator
baseurl=http://autoinstall.plesk.com/PMM_0.1.10/thirdparty-rpm-CentOS-7-x86_64
enabled=1
gpgcheck=0`

**Comment by gregarios** [comment]
I removed the migration repo completely from Yum and restarted but I still gett he same error. Upon looking at the logs, it seems it is from a new repo your Alma update installs? See here:

```
2023-04-28 08:21:06,073 - INFO - No matches found for the following disable plugin patterns: subscription-manager
2023-04-28 08:21:06,073 - INFO - Repository extras is listed more than once in the configuration
2023-04-28 08:21:06,073 - INFO - Repository extras-source is listed more than once in the configuration
2023-04-28 08:21:06,073 - INFO - Errors during downloading metadata for repository 'alma-plesk-migrator-tp':
2023-04-28 08:21:06,073 - INFO - - Status code: 404 for http://autoinstall.plesk.com/PMM_0.1.11/thirdparty-rpm-RedHat-el8-x86_64/repodata/repomd.xml (IP: 212.102.46.9)
2023-04-28 08:21:06,074 - INFO - Error: Failed to download metadata for repo 'alma-plesk-migrator-tp': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

```

Attached is a new complete log.
[Server-Upgrade-Failed-log-20230428.txt.zip](https://github.com/plesk/centos2alma/files/11355163/Server-Upgrade-Failed-log-20230428.txt.zip)

**Comment by gregarios** [comment]
Also, It seems the alma-plesk-migrator-tp repo, which I cannot find, requests the missing repo file too.
Attached is the leapp-preupgrade.log -- do a search for "Errors during downloading metadata for repository" in it to see more errors.

[Server-Upgrade-Failed-leapp-preupgrade.log-20230428.txt.zip](https://github.com/plesk/centos2alma/files/11355386/Server-Upgrade-Failed-leapp-preupgrade.log-20230428.txt.zip)

**Comment by SandakovMM** [comment]
I have incorporated some changes that should stop Leapp from utilizing the third-party repository during the conversion process. Related PR - #93.
It will not help if the thirdparty repository already leaked into leapp configs, but should prevent the problem on new conversion

**Comment by gregarios** [comment]
Another fail from a fresh backup of my server. Before I started I made sure the Plesk Migrator repo files were all removed.
I got the same errors as before, then I went in looking for the migrator repo references you mentioned above but found none.
Here are the current contents of the two leapp files you mentioned:

` cat /etc/leapp/files/repomap.csv
CentOS 7 repoid,AlmaLinux 8 repoid in custom repo file,AlmaLinux 8 repo name in PES,CentOS 7 minor versions,AlmaLinux 8 minor versions,architecture,type(rpm/srpm/debuginfo),source product type (ga/beta,htb),target product type (ga/beta/htb)

# Version: 1
# Date: 20210726

# x86_64
base,almalinux8-baseos,almalinux8-baseos,all,all,x86_64,rpm,ga,ga
base,almalinux8-appstream,almalinux8-appstream,all,all,x86_64,rpm,ga,ga
base,almalinux8-powertools,almalinux8-powertools,all,all,x86_64,rpm,ga,ga
base,almalinux8-ha,almalinux8-ha,all,all,x86_64,rpm,ga,ga
base,almalinux8-resilientstorage,almalinux8-resilientstorage,all,all,x86_64,rpm,ga,ga

updates,almalinux8-baseos,almalinux8-baseos,all,all,x86_64,rpm,ga,ga
updates,almalinux8-appstream,almalinux8-appstream,all,all,x86_64,rpm,ga,ga
updates,almalinux8-powertools,almalinux8-powertools,all,all,x86_64,rpm,ga,ga
updates,almalinux8-ha,almalinux8-ha,all,all,x86_64,rpm,ga,ga
updates,almalinux8-resilientstorage,almalinux8-resilientstorage,all,all,x86_64,rpm,ga,ga
extras,almalinux8-extras,almalinux8-extras,all,all,x86_64,rpm,ga,ga
epel,alma-epel,alma-epel,all,all,x86_64,rpm,ga,ga
epel-debuginfo,alma-epel-debuginfo,alma-epel-debuginfo,all,all,x86_64,rpm,ga,ga
epel-source,alma-epel-source,alma-epel-source,all,all,x86_64,rpm,ga,ga
mariadb,alma-mariadb,alma-mariadb,all,all,x86_64,rpm,ga,ga
`


`cat /etc/leapp/files/leapp_upgrade_repositories.repo
[almalinux8-baseos]
name=AlmaLinux 8 - BaseOS
mirrorlist=https://mirrors.almalinux.org/mirrorlist/8/baseos
# baseurl=https://repo.almalinux.org/almalinux/8/BaseOS/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[almalinux8-appstream]
name=AlmaLinux 8 - AppStream
mirrorlist=https://mirrors.almalinux.org/mirrorlist/8/appstream
# baseurl=https://repo.almalinux.org/almalinux/8/AppStream/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[almalinux8-powertools]
name=AlmaLinux 8 - PowerTools
mirrorlist=https://mirrors.almalinux.org/mirrorlist/8/powertools
# baseurl=https://repo.almalinux.org/almalinux/8/PowerTools/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[almalinux8-highavailability]
name=AlmaLinux 8 - HighAvailability
mirrorlist=https://mirrors.almalinux.org/mirrorlist/8/ha
# baseurl=https://repo.almalinux.org/almalinux/8/HighAvailability/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[almalinux8-resilientstorage]
name=AlmaLinux 8 - ResilientStorage
mirrorlist=https://mirrors.almalinux.org/mirrorlist/8/resilientstorage
# baseurl=https://repo.almalinux.org/almalinux/8/ResilientStorage/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[almalinux8-extras]
name=AlmaLinux 8 - Extras
mirrorlist=https://mirrors.almalinux.org/mirrorlist/8/extras
# baseurl=https://repo.almalinux.org/almalinux/8/extras/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[alma-epel]
name=Alma Extra Packages for Enterprise Linux 8 - $basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch&infra=$infra&content=$contentdir
# It is much more secure to use the metalink, but if you wish to use a local mirror
# place its address here.
#baseurl=http://download.example/pub/epel/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8

[alma-epel-debuginfo]
name=Alma Extra Packages for Enterprise Linux 8 - $basearch - Debug
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-debug-8&arch=$basearch&infra=$infra&content=$contentdir
# It is much more secure to use the metalink, but if you wish to use a local mirror
# place its address here.
#baseurl=http://download.example/pub/epel/7/$basearch/debug
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
gpgcheck=1

[alma-epel-source]
name=Alma Extra Packages for Enterprise Linux 8 - $basearch - Source
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-source-8&arch=$basearch&infra=$infra&content=$contentdir
# It is much more secure to use the metalink, but if you wish to use a local mirror
# place it's address here.
#baseurl=http://download.example/pub/epel/7/source/tree/
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
gpgcheck=1

[alma-mariadb]
name=Alma MariaDB
baseurl=https://mirror.rackspace.com/mariadb/yum/10.11/centos8-amd64
gpgkey = https://mirror.rackspace.com/mariadb/yum/RPM-GPG-KEY-MariaDB
gpgcheck=1
`

**Comment by SandakovMM** [comment]
The issue is occurring due to the presence of the https://mirror.rackspace.com/mariadb/yum/10.11/ repository.  It seems that we are trying to map the currently used https://mirror.rackspace.com/mariadb/yum/10.11/centos7-amd64 to https://mirror.rackspace.com/mariadb/yum/10.11/centos8-amd64, but there is no such repository available. The correct mapping target should be https://mirror.rackspace.com/mariadb/yum/10.11/rhel8-amd64. I will verify the mapping on our end and update you with the results.

**Comment by SandakovMM** [comment]
I've merged Rackspace mariadb repository support, related PR - #96.
To proceed with the conversion, remove the already added Rackspace repository mapping from the leapp_upgrade_repositories.repo.txt. Additionally, you could just change URL for the mapping, but note, that the repository adoption step in the finishing stage will be failed in this case.

**Comment by SandakovMM** [comment]
No, released version don't contains changes I mentioned before.Let me just provide last build here.
[centos2alma.zip](https://github.com/plesk/centos2alma/files/11383332/centos2alma.zip)

**Comment by gregarios** [comment]
> No, released version don't contains changes I mentioned before.Let me just provide last build here. [centos2alma.zip](https://github.com/plesk/centos2alma/files/11383332/centos2alma.zip)

That made it a lot further! When it needed to reboot, it just disconnected me (I only have SSH access to the server on Google Cloud).  It would be nice if it gave a notice with a pause requiring a continue in order to get the message that it needed to reboot, as I just couldn't connect again indefinitely... after an hour of waiting for it to do something, I forced the server to shut down in the GCE Instance controls and it then booted back up and continued as seen in the log.

Nevertheless, it again failed but this time with a new problem seen at the end of the log attached:
[centos2alma-20230503a.log.txt.zip](https://github.com/plesk/centos2alma/files/11384952/centos2alma-20230503a.log.txt.zip)

It seems AlmaLinux was installed, but failed to update the apps.

**Comment by SandakovMM** [comment]
> When it needed to reboot, it just disconnected me (I only have SSH access to the server on Google Cloud). It would be nice if it gave a notice with a pause requiring a continue in order to get the message that it needed to reboot

We will consider adding a 30-second pause before initiating the reboot to allow users to stop the process if they wish to avoid the reboot. However, the automatic reboot is necessary anyway, as we expect users to convert multiple servers and it would be inconvenient to switch between all of them to proceed with the conversion.
It is worth noting that after the preparation stage is completed, the server becomes inapplicable because all Plesk-related services are stopped and some conflicting packages are removed. Plesk can be restored using the `./centos2alma --revert` command, but it is intended to be used mostly if the conversion cannot proceed.
To prevent reboot you could use hidden option --no-reboot. I could make it visible in the help message if you think it is necessary.

> Nevertheless, it again failed but this time with a new problem seen at the end of the log attached:

It looks like the Plesk repositories are disabled during this step. So when the tool trying to install fail2ban it fails to find some dependencies.
Could you please provide a feedback archive from your host? You could create it by calling `./centos2alma --prepare-feedback`.

**Comment by gregarios** [comment]
> Could you please provide a feedback archive from your host? You could create it by calling `./centos2alma --prepare-feedback`.

Yes I'll run through the install again and get this for you.



> We will consider adding a 30-second pause before initiating the reboot to allow users to stop the process if they wish to avoid the reboot. However, the automatic reboot is necessary anyway, as we expect users to convert multiple servers and it would be inconvenient to switch between all of them to proceed with the conversion.

I'm not looking to avoid the reboot, but rather just know that it is happening. Maybe while "paused" for a minute the status here could read "REBOOTING IN ONE MINUTE" so it can be known what's happening:
![screenshot-20230504-64416-AM](https://user-images.githubusercontent.com/7989224/236225450-217d53d8-3dab-4e86-a754-cc5be03b9301.jpg)

Also, my GCE instance did not seem to "reboot" when this happened, but rather just stopped. I had to manually turn it off and back on to get it back up. The only indicator that something wasn't right was that the CPU readings in the Google monitoring tools were showing no activity after it "rebooted" itself. I waited about an hour then forced it off and back on like a power button. Seems like there needs to be some kind of notification possibility for those of us without any screen capability to our server?

**Comment by gregarios** [comment]
What the heck?! It worked this time? How can this be? I started with a clone of the previous try before it was attempted.
No errors this time. This is disturbing since I don't know what the problem was I can't be sure what the production server will do...
![screenshot-20230504-71804-AM](https://user-images.githubusercontent.com/7989224/236235989-16872ddc-a9ca-4e58-9152-bc4529db2bfb.jpg)

Any ideas?

**Comment by SandakovMM** [comment]
> my GCE instance did not seem to "reboot" when this happened, but rather just stopped. I had to manually turn it off and back on to get it back up.

Unfortunately, there is no way to monitor the conversion process when it is in the temporary OS. Since it is specialized for conversion, it does not have a network interface up, so there is no way to connect to it. This is why we advise having a console connection. It is the simplest way to monitor the conversion process inside the temporary OS. We have been looking for ways to make it possible to monitor the conversion process without a console connection, but so far, we have had no success.

> Any ideas?

I assume the problem was caused by disabled Plesk repositories, hoping the feedback archive could confirm it. Let me try to find a way to reproduce the problem on my side. About why the problem didn't repeat - maybe it was fixed by plesk daily maintenance.

> Seems the Plesk Settings for each hosted domain are defaulted.

Do you mean nginx/apache configurations, or something you configured inside the Plesk interface? Have you tried running `plesk repair` to see if it helps?

**Comment by gregarios** [comment]
> Do you mean nginx/apache configurations, or something you configured inside the Plesk interface? Have you tried running `plesk repair` to see if it helps?

Yes, the nginx/apache directives were default for the domain.

I ran plesk repair fully on the server and it did not fix it.

I will revert my test server back, take some screenshots of the domain settings, then convert it again and compare. I'll let you know the results and do another `./centos2alma --prepare-feedback`

**Comment by gregarios** [comment]
Ok I tried it again. Seems I didn't have any settings in there after all so it wasn't defaulted. Forget that problem.

Again, it installed AlmaLinux and I am able to log in to Plesk on it. However, the domain hosted is not accessible again. Everything in it's settings appears to be ok, but I get a "502 Bad gateway" error when trying to visit the site, and error messages in the log like this:

`2023/05/05 10:01:19 [crit] 48354#0: *9 connect() to 10.138.0.7:7081 failed (13: Permission denied) while connecting to upstream, client: 24.113.95.49, server: askb.org, request: "GET / HTTP/2.0", upstream: "https://10.138.0.7:7081/", host: "askb.org"`

I did run the feedback and gathered the centos2alma.log as well and here they are:
[centos2alma_feedback_20230505.zip](https://github.com/plesk/centos2alma/files/11408558/centos2alma_feedback_20230505.zip)
[centos2alma-20230505.log.zip](https://github.com/plesk/centos2alma/files/11408559/centos2alma-20230505.log.zip)

I ran `plesk repair all -y -verbose` and it completed with no errors showing and nothing to fix.

Here is the server info showing:
```
Product version: Plesk Obsidian 18.0.52.2
OS version: AlmaLinux 8.7 x86_64
Build date: 2023/05/02 13:00
Revision: 1c44bda10dedda3c088c3da0271c725d3e2ec53b
```

**Comment by gregarios** [comment]
Next problem: Spamassassin will not launch.
[spamassassin-startup-messages.log.txt.zip](https://github.com/plesk/centos2alma/files/11411515/spamassassin-startup-messages.log.txt.zip)

Doesn't appear to be an SELinux issue this time.
Ran plesk repair and it finds nothing.
Trying to turn on or off the mail filter settings in the UI causes Plesk to crash and go into the repair UI.

**Comment by SandakovMM** [comment]
> The main SELinux rule update that fixed a host of problems was:

Could you please verify if the httpd_can_network_connect was disabled prior to the conversion? As far as I am aware, leapp does not attempt to modify SELinux options directly; it only triggers relabeling during the initial boot after the conversion.

> Next problem: Spamassassin will not launch.
> ...
> running anything needing Perl produces this fatal error: /usr/bin/perl: symbol lookup error: /usr/local/lib64/perl5/auto/Cwd/Cwd.so: undefined symbol: Perl_xs_version_bootcheck

It is likely that a Perl-related package was not updated during the conversion. Could you please provide the package that provides the library file by running rpm -qf /usr/local/lib64/perl5/auto/Cwd/Cwd.so?

**Comment by gregarios** [comment]
> Could you please verify if the httpd_can_network_connect was disabled prior to the conversion? As far as I am aware, leapp does not attempt to modify SELinux options directly; it only triggers relabeling during the initial boot after the conversion.

Both before and after they are enabled. However, there are new entries in the updated version. Here are the output of  `semanage boolean -l` before and after the upgrade:
[selinux_original_settings.txt.zip](https://github.com/plesk/centos2alma/files/11421719/selinux_original_settings.txt.zip)
[selinux_updated_settings.txt.zip](https://github.com/plesk/centos2alma/files/11421718/selinux_updated_settings.txt.zip)


> It is likely that a Perl-related package was not updated during the conversion. Could you please provide the package that provides the library file by running rpm -qf /usr/local/lib64/perl5/auto/Cwd/Cwd.so?

I get this:
`file /usr/local/lib64/perl5/auto/Cwd/Cwd.so is not owned by any package`

**Comment by SandakovMM** [comment]
> Both before and after httpd_can_network_connect is enabled.

I have noticed that centos2alma sets selinux status to enforced even if it was disabled before the conversion. I've fixed this behaviour - PR #103.
Just to confirm, is SELinux in enforcing mode on your system during the conversion?

**Comment by gregarios** [comment]
> Just to confirm, is SELinux in enforcing mode on your system during the conversion?

It may have been, actually. In retrospect I should have turned it off.

**Comment by SandakovMM** [comment]
> Here is the output of perl -V on the machine pre-upgrade. Does this tell you anything?

Not really, it's actually the same perl as my own. I believe the problem in the library itself. Could you check if `rpm -qf /usr/local/lib64/perl5/auto/Cwd/Cwd.so` will show something adequate on CentOS 7 (before upgrade) by any chance?

**Comment by gregarios** [comment]
> Could you check if `rpm -qf /usr/local/lib64/perl5/auto/Cwd/Cwd.so` will show something adequate on CentOS 7 (before upgrade) by any chance?

It says:
`file /usr/local/lib64/perl5/auto/Cwd/Cwd.so is not owned by any package`

**Comment by gregarios** [comment]
```
# rpm -qf /usr/local/lib64/perl5/auto/Cwd/Cwd.so
file /usr/local/lib64/perl5/auto/Cwd/Cwd.so is not owned by any package
# ll /usr/local/lib64/perl5/auto/Cwd/Cwd.so
-r-xr-xr-x. 1 root root 84K Feb 24  2020 /usr/local/lib64/perl5/auto/Cwd/Cwd.so
# ll /usr/local/lib64/perl5/auto/Cwd/
total 88K
-r-xr-xr-x. 1 root root 84K Feb 24  2020 Cwd.so
-rw-r--r--. 1 root root 988 Feb 24  2020 .packlist
# cat /usr/local/lib64/perl5/auto/Cwd/.packlist 
/usr/local/lib64/perl5/Cwd.pm
/usr/local/lib64/perl5/File/Spec.pm
/usr/local/lib64/perl5/File/Spec/AmigaOS.pm
/usr/local/lib64/perl5/File/Spec/Cygwin.pm
/usr/local/lib64/perl5/File/Spec/Epoc.pm
/usr/local/lib64/perl5/File/Spec/Functions.pm
/usr/local/lib64/perl5/File/Spec/Mac.pm
/usr/local/lib64/perl5/File/Spec/OS2.pm
/usr/local/lib64/perl5/File/Spec/Unix.pm
/usr/local/lib64/perl5/File/Spec/VMS.pm
/usr/local/lib64/perl5/File/Spec/Win32.pm
/usr/local/lib64/perl5/auto/Cwd/Cwd.so
/usr/local/share/man/man3/Cwd.3pm
/usr/local/share/man/man3/File::Spec.3pm
/usr/local/share/man/man3/File::Spec::AmigaOS.3pm
/usr/local/share/man/man3/File::Spec::Cygwin.3pm
/usr/local/share/man/man3/File::Spec::Epoc.3pm
/usr/local/share/man/man3/File::Spec::Functions.3pm
/usr/local/share/man/man3/File::Spec::Mac.3pm
/usr/local/share/man/man3/File::Spec::OS2.3pm
/usr/local/share/man/man3/File::Spec::Unix.3pm
/usr/local/share/man/man3/File::Spec::VMS.3pm
/usr/local/share/man/man3/File::Spec::Win32.3pm
```

**Comment by gregarios** [comment]
> You can try executing the following command: cpan -r Cwd

I assume you mean before doing the AlmaLinux upgrade?

**Comment by SandakovMM** [comment]
> I assume you mean before doing the AlmaLinux upgrade?

I believe it doesn't really matter, and you can reinstall the modules after the conversion as well. However, I'm not entirely certain as I'm not familiar with the inner workings of cpan.

**Comment by gregarios** [comment]
> I believe it doesn't really matter, and you can reinstall the modules after the conversion as well. However, I'm not entirely certain as I'm not familiar with the inner workings of cpan.

Unfortunately, cpan is one of the things not working after the upgrade because of the Cwd error.

**Comment by SandakovMM** [comment]
> Unfortunately, cpan is one of the things not working after the upgrade because of the Cwd error.

Oh, in that case, the option to recompile the module seems to be unacceptable now. Good to know.

By the way, I will attempt to reproduce the problem on my end to confirm if the modules installed from cpan are causing the issue..

**Comment by SandakovMM** [comment]
Likely the /usr/lib64/perl5/vendor_perl/auto/Cwd/Cwd.so was installed by the perl_PathTools package. Example from my instance:
```shell
# rpm -qf /usr/lib64/perl5/vendor_perl/auto/Cwd/Cwd.so
perl-PathTools-3.40-5.el7.x86_64
```
Maybe you even could fully remove the one that was installed by cpan.

**Comment by gregarios** [comment]
> Maybe you even could fully remove the one that was installed by cpan.

When you say "remove" do you mean, say:
`mv /usr/local/lib64/perl5/auto/Cwd /home/gjpiper/storage/Cwd.bak`

Is there a method? I've never removed anything from perl.

**Comment by SandakovMM** [comment]
I have added the reinstallation of modules installed by CPAN and a checker to verify if the modules are in our mapping list (#104). I believe this should help with your problem.
However, if you have additional modules installed from CPAN, the conversion may fail during the Perl modules check. In such cases, you can use the --remove-unknown-perl-modules flag to force the conversion.

**Comment by gregarios** [comment]
I will be trying the upgrade with a fresh clone of my server in the next few days. I will keep this thread "unclosed" to see if anything else unexpected happens on the next run. (if that works for you)
Thank you so much for your help! You really filled in the blanks in my knowledge to help me through this. So far so good.

Any chance there will be a new release of the script soon?

**Comment by SandakovMM** [comment]
> Any chance there will be a new release of the script soon?

Sure, we have plans to publish new release by 5th of June.

**Comment by gregarios** [comment]
> Sure, we have plans to publish new release by 5th of June.
If you would, can you send me a "nightly" again so I can try your latest beta update this round?

**Comment by SandakovMM** [comment]
Sure. Here it is [centos2alma.zip](https://github.com/plesk/centos2alma/files/11474134/centos2alma.zip)

**Comment by gregarios** [comment]
> Sure. Here it is [centos2alma.zip](https://github.com/plesk/centos2alma/files/11474134/centos2alma.zip)

This is much improved, and in fact works quite well. I upgraded again and the server was still up and functioning, as were most of the Perl modules even from CPAN that were installed. I only see one problem with my install I can't seem to fix:
My original SpamAssasin installation (v3.4.6 running on Perl v5.16.3) is running and filtering mailboxes, but the RelayCountry MaxMind plugin is no longer working. Spamassassin just doesn't even recognize it. I reinstalled and am troubleshooting but it just won't recognize the plugin — as if it wasn't installed:
**Mail::SpamAssassin::Plugin::RelayCountry**
CPAN says it is installed and up to date.

The MaxMind GeoIP2 database is installed and working fine with Apache, Nginx, and even WordPress, but I can't get SpamAssasin to use it. Maybe it is the new version of Perl? Or something else.

**Comment by gregarios** [comment]
> If you happen to find a way to install the RelayCountry module on AlmaLinux, please feel free to share the installation instructions with us or provide a pull request with an action to install the module within the conversion tool.

I will indeed. Not sure why reinstalling is being difficult on my server. Think I'm missing a crucial piece of experience.

**Comment by gregarios** [comment]
> If you happen to find a way to install the RelayCountry module on AlmaLinux, please feel free to share the installation instructions with us or provide a pull request with an action to install the module within the conversion tool.

Ok so I worked for two days trying to figure out how to get RelayCountry to be recognized by SpamAssassin...
Only after I did this ridiculously simple idea did it work:
In order to keep all the updater software (yum, cpan) from trying to install SpamAssasin 4 every time I needed a module for SpamAssassin 3.4 I downloaded the Mail-SpamAssassin-3.4.6.tar.gz tarball directly from Apache, retrieved the RelayCountry.pm file out of it, and placed it here where it instantly began working:
`/usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/`

Also, after a few other Perl script problems trying to load using GeoIP2 I figured out that this Perl module location is not apparently being recognized by my Perl scripts, and that may be a big issue with all the Perl modules:
`/usr/share/perl5/vendor_perl/`

In this case I got it to work by by loading the Perl module directly in the script using this:
`use lib '/usr/share/perl5/vendor_perl';`

Maybe these are related somehow, and can be of help in your script.

**Comment by gregarios** [comment]
I took the dive and upgraded my production server to AlmaLinux 8.8 and it all worked as expected!
Thank you for all your support in this!
I'm good to 2029!

If you get a chance to create an update script from AL8 to AL9 I'll be all for it. :-)

**Comment by SandakovMM** [comment]
Hay @gregarios,
I'm delighted to hear that! =)
Thank you for your assistance. We have made significant improvements to the tool during the resolution of this issue.
